/*
 * Text for the plot-selection and analysis-progress screens, in both languages.
 * `en` must have exactly the same shape as `ar` (TypeScript checks this).
 */

const ar = {
  select: {
    title: "اختيار القطعة",
    subtitle: "حدد قطعتك السكنية في الرياض لبدء التحليل.",
    method: "طريقة الاختيار",
    modeMap: "نقر مباشر على الخريطة",
    modeCoords: "إدخال الإحداثيات",
    mapHint: "انقر على قطعتك في الخريطة. قرّب الخريطة للوصول إلى القطعة بدقة.",
    latitude: "خط العرض",
    longitude: "خط الطول",
    search: "بحث",
    coordsHint: "مثال: 24.7136 و 46.6753",
    errMissing: "أدخل خط العرض وخط الطول.",
    errInvalid: "الإحداثيات غير صحيحة. خط العرض بين -90 و 90، وخط الطول بين -180 و 180.",
    errOutside: "هذا الموقع خارج مدينة الرياض. اختر قطعة داخل الرياض.",
    found: "تم تحديد الموقع على الخريطة.",
    plotTitle: "القطعة المحددة",
    plotEmpty: "لم تحدد قطعة بعد.",
    plotLoading: "جاري جلب بيانات القطعة…",
    coordinates: "الإحداثيات",
    area: "المساحة",
    areaUnit: "م²",
    neighborhood: "الحي",
    orientation: "الاتجاه",
    mockTag: "بيانات تجريبية",
    start: "تأكيد القطعة وبدء التحليل",
    mapLabel: "خريطة اختيار القطعة",
    mapLoading: "جاري تحميل الخريطة…",
    directions: {
      north: "شمال",
      northEast: "شمال شرق",
      east: "شرق",
      southEast: "جنوب شرق",
      south: "جنوب",
      southWest: "جنوب غرب",
      west: "غرب",
      northWest: "شمال غرب",
    },
  },
  analyzing: {
    title: "جاري تحليل موقعك",
    subtitle: "نجمع بيانات الموقع ونحلّلها. لن نعرض أي نتائج ناقصة.",
    steps: [
      "جلب بيانات البيئة الطبيعية (الشمس والرياح)",
      "جلب بيانات المباني والقطع المجاورة",
      "تطبيق نموذج الذكاء الاصطناعي",
      "الفحص التنظيمي (كود البناء السعودي)",
    ],
    done: "اكتمل التحليل. جاري فتح النتائج…",
    failTitle: "تعذر إكمال التحليل",
    failText: "لم نتمكن من جمع البيانات المطلوبة، لذلك لن نعرض نتائج ناقصة. حاول مرة أخرى.",
    retry: "إعادة المحاولة",
    back: "العودة لاختيار القطعة",
    defaultName: "مشروع",
  },
};

export type PlotCopy = typeof ar;

const en: PlotCopy = {
  select: {
    title: "Select your plot",
    subtitle: "Pick your residential plot in Riyadh to start the analysis.",
    method: "Selection method",
    modeMap: "Click on the map",
    modeCoords: "Enter coordinates",
    mapHint: "Click your plot on the map. Zoom in to reach the plot accurately.",
    latitude: "Latitude",
    longitude: "Longitude",
    search: "Search",
    coordsHint: "Example: 24.7136 and 46.6753",
    errMissing: "Enter both latitude and longitude.",
    errInvalid: "Invalid coordinates. Latitude is between -90 and 90, longitude between -180 and 180.",
    errOutside: "This location is outside the city of Riyadh. Choose a plot inside Riyadh.",
    found: "The location was found on the map.",
    plotTitle: "Selected plot",
    plotEmpty: "No plot selected yet.",
    plotLoading: "Loading plot details…",
    coordinates: "Coordinates",
    area: "Area",
    areaUnit: "m²",
    neighborhood: "Neighborhood",
    orientation: "Orientation",
    mockTag: "Sample data",
    start: "Confirm plot and start analysis",
    mapLabel: "Plot selection map",
    mapLoading: "Loading the map…",
    directions: {
      north: "North",
      northEast: "North-east",
      east: "East",
      southEast: "South-east",
      south: "South",
      southWest: "South-west",
      west: "West",
      northWest: "North-west",
    },
  },
  analyzing: {
    title: "Analyzing your site",
    subtitle: "We are collecting and analyzing site data. We will never show incomplete results.",
    steps: [
      "Collecting environmental data (sun and wind)",
      "Collecting neighboring buildings and plots",
      "Running the AI model",
      "Regulatory check (Saudi Building Code)",
    ],
    done: "Analysis complete. Opening your results…",
    failTitle: "The analysis could not be completed",
    failText: "We could not collect the required data, so we will not show incomplete results. Please try again.",
    retry: "Try again",
    back: "Back to plot selection",
    defaultName: "Project",
  },
};

export const plotCopy = { ar, en };